### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by VladislavArzamastsev2** [VladislavArzamastsev2/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by VL4DYSL4V** [comment]
**Timeline**
April 21, 1926: I was born to the Duke and Duchess of York

1936: My father becomes King George VI, and I become first in line to the throne.

October, 1940: I deliver my first public speech on the BBC’s Children’s Hour 
radio program, addressing children who had to be evacuated because of the war.

1945: I was made a Subaltern in the Auxiliary Territorial Service,  and by the end of the war, 
reached the rank of Junior Commander. I became a qualified driver and mechanic and drived a military truck.

November 20, 1947: I married Lieutenant Philip Mountbatten

November 14, 1948: I have my first child, Prince Charles.

August 15, 1950: I have a daughter, Princess Anne.

February 6, 1952: My father, King George VI, dies. I accede to the throne. 

June 2, 1953: My coronation. It is the first time television cameras are allowed inside 
 Westminster Abbey for a state function.

1957: I visit New York and address the United Nations General Assembly. On
 the same tour, I visit Ottawa and open Parliament.

1960s: The British Empire slowly shrinks as countries in Africa and elsewhere gain independence.
 I eventually remain head of state for 15 countries outside of  the United Kingdom

February 19, 1960: I give birth to Prince Andrew, my third child.

March 10, 1964: I give birth to Prince Edward, my fourth and last child.

July 1, 1969: Charles is named the Prince of Wales and heir to the throne.

September 14, 1981: Shots are fired as I participate in the annual Trooping 
 the Colour ceremony. It turns out that they were blanks, fired by a teenager.

1982: The Pope visits England, the first pope to do so in 450 years. I receive
 him in my capacity as the head of the Church of England.

1992: “Annus horribilus.” Prince Andrew and his wife separate, Princess Anne divorces
 her husband, Prince Charles formally separates from his wife Diana, and a significant
 portion of Windsor Castle is destroyed by fire.

August 31, 1997: Princess Diana is killed in a car crash in Paris. 

1999: I open the newly-created National Assembly for Wales and the Scottish Parliament.

2013 - The Succession to the Crown Act. The Act replaced male-preference primogeniture
 with absolute primogeniture for those in the line of succession born after
 28 October 2011, which means the eldest child, regardless of sex, precedes any siblings

2015, September 9: I become the longest-reigning monarch.

2017, February 6: I celebrate my Sapphire Jubilee, marking 65 years since I ascended the throne.



**Responsibilities:** 
_Head of State_
         As Head of State, I go on official State visits abroad. 
	 I also invite other world leaders to come to the United Kingdom. 

_Head of the Armed Forces_
         I am the only person who can declare when the country is at war and
	 when war is over, although I must take advice from the government first.

_Head of the Church of England_
         This is a position that all British monarchs have held since 1530s.
         I appoint archbishops and bishops on the advice of the Prime Minister.

_Government Duties_
         Every day 'red boxes' are delivered to my desk full of documents
	 and reports from the government ministers and Commonwealth officials. 
	 They must all be read and, if necessary, signed by me.

_Represent the Nation_
         I represent the nation at times of great celebration or sorrow.
	 One example of this is Remembrance Day ceremony at the Cenotaph monument 
	 in Whitehall. I lay a wreath there each year to honour the members 
	 of the armed forces who have died fighting for our country.

_Royal Garden Parties_
         At least three Royal Garden Parties are held at Buckingham Palace each year
	 and about 8,000 guests attend each one.

_Visits_
         Alongside my other duties I spend a huge amount of time travelling
	 around the country visiting hospitals, schools, factories and other places and organisations.
